### ISSUE TITLE
"Operation was cancelled" message with gvfs-mtp -- but harmless

### ISSUE THREAD

**Issue by grego** [lxqt/pcmanfm-qt#1041]
##### Expected Behavior
I'm trying to copy files to my phone, mount using gvfs-mtp. GTK Pcmanfm lists all files and manages copying fine, without errors.

##### Current Behavior
When I open the device and then the _Internal Shared Storage_ folder within it, I get an error saying `Operation was cancelled`. However, the file manager proceeds to lists all the files as expected. Copying single files works, however when I try to copy a directory, `Operation not supported` error gets displayed with only the new folder being created on the device and nothing being copied into it. Nothing appears in the logs.

##### Steps to Reproduce (for bugs)

1.  Mount a mobile device using MTP
2.  Try to copy a folder into it. 

##### System Information

* Distribution: Arch Linux
* Kernel: 5.3.13-arch1-1
* Qt Version: 5.13.2-3
* libfm-qt Version: 5.13.2-3
* libqtxdg Version: 3.4.0-1
* lxqt-build-tools Version: none
* Package version: 0.14.1-1

All packages from Arch repos.

**Comment by tsujan** [comment]
Fixed ages ago, in git.

You have Arch, so it should be easy for you to use git packages. That's recommended if you want to get rid of old bugs -- especially with libfm-qt+pcmanfm-qt.

**Comment by grego** [comment]
When using the git version, copying files works, but I still get `Operation was cancelled` pop-up when I open an MTP folder, albeit everything works as expected afterwards.

**Comment by tsujan** [comment]
> but I still get Operation was cancelled pop-up

Never happens here.

If you found the right circumstances, under which it happens, please leave a comment here -- the circumstances you mentioned before isn't sufficient for triggering the problem; I mean this:

> When I open the device and then the Internal Shared Storage folder within it, I get an error saying `Operation was cancelled`.

**Comment by tsujan** [comment]
At last, I succeeded in seeing the error message randomly, under very unusual circumstances: I turned off the desktop module and double clicked the mounted item very fast.

So, there's definitely a problem. Since it happens very rarely and randomly here but often for you, it should be about timing. And yes, the error message seems harmless.

Reopening…

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/libfm-qt/pull/493

Such error messages are useless and annoying. I hope this was the last one but if similar cases happen, I'll eradicate all of them together.
