### ISSUE TITLE
ease completion in address bar

### ISSUE THREAD

**Issue by pmattern** [lxqt/pcmanfm-qt#201]
Right now there's no means to complete paths in address bar by hitting a single key, in particular `Tab` is keeping its usual functionality to jump between UI elements if the cursor is in address bar.
Also, the drop-down list presenting subdirectories of the directory that's actually in address bar gets displayed only if a trailing slash is suffixed.
Altogether this makes manually filing paths in address bar a rather cumbersome task: the first directory of both absolute and relative paths always has to be typed completely including the trailing slash. Typing following subdirectories can be avoided by picking them from the said drop-down menu only and still the following trailing slashes have to be typed manually.

All in all I'd suggest to make an exception and assign the `Tab` key a completion functionality similar to the one known from shells as soon as the cursor is in address bar. It would be good if this functionality could already be applied to the first directory of the path to be filed, too.

**Comment by stefonarch** [comment]
+1, it's one of the things I miss mostly.

**Comment by PCMan** [comment]
Fixed, finally. :-)
https://github.com/lxde/libfm-qt/commit/374abd283fe131ad2c9f1550fb9355770decc8eb

**Comment by pmattern** [comment]
Unfortunately two problems remain which are pretty much impairing the UX, IMO:

Autocompletion doesn't comprise the trailing slash. E. g. filing `/us` + hitting `Tab` yields `/usr` instead of `/usr/`.
This makes paths comprising several levels of directories much more complicated to enter. Also, the list displaying subdirectories of the current one comes up only when the trailing slash is available (which can be considered expected behaviour).

This list is empty most of the time like in this screenshot
![pcmanfm-qt_addressbar-vs-tab_empty-list](https://cloud.githubusercontent.com/assets/9860801/12532547/fa9359a8-c216-11e5-848c-67d157d757f8.png)
generated after filing `/us`, hitting `Tab` and complementing the trailing slash manually.

While testing I stumbled upon one more thing which would be pretty good to have:
Sometimes it is necessary to interrupt filing a new path, e. g. if a user recalls he still has to look something up in the "old" directory before changing into the "new" one. In such cases it would be very nice if hitting `Esc` restored the old directory's path in the address bar.
Right now PCManFM-Qt keeps displaying the old directory in the actual file manager view but any remnants of a new directory's path that had already been filed in the address bar before hitting `Esc` as well.

lxde/libfm-qt@a197e6d and lxde/pcmanfm-qt@c7fe595 on Arch Linux. All the said three features are working in PCManFM's GTK flavour.

**Comment by PCMan** [comment]
OK, let's fix it.

**Comment by stefonarch** [comment]
To fix before the release? It's quite annoying.

**Comment by PCMan** [comment]
@tsujan Would you please help this part? Don't really have the time ATM. :-(

**Comment by tsujan** [comment]
> @tsujan Would you please help this part? Don't really have the time ATM. :-(

Oh, sorry! I hadn't seen your message and was led here by Google because of another problem. I'll look into it.

**Comment by tsujan** [comment]
@pmattern 
Which behavior is desirable?

(1) An ending slash should appear after using tab (and, as a result, another auto-completion list is shown)?
(2) An ending slash should appear after selecting from the completion list and pressing esc (and again, another auto-completion list is shown)?
(3) The folder should be opened with tab auto-completion?
(4) An ending slash should always be added when a folder is opened?
Or...?

With both (1) and (2), we would have an ever-present auto-completion list, which would be annoying, IMO.

**Comment by tsujan** [comment]
> ... Sometimes it is necessary to interrupt filing a new path... In such cases it would be very nice if hitting Esc restored the old directory's path in the address bar... Right now PCManFM-Qt keeps displaying the old directory in the actual file manager view but any remnants of a new directory's path that had already been filed in the address bar before hitting Esc as well.

https://github.com/lxde/pcmanfm-qt/pull/371/commits/1aa27b7381b63cb46cb4990de6f259cf281b47aa fixes that.

**Comment by joshuakraemer** [comment]
I would like to have the following behaviour, similar to how the usual shells work:

- Pressing tab after a slash invokes the full (neutral) auto-completion list.
- Pressing tab after another character triggers autocompletion (additional characters are added).
- If the given characters unambiguously define a folder, the full foldername and a trailing slash are added.
(Optional: a new, neutral auto-completion list is automatically shown.*)
- Now one can immediately continue typing characters or pressing tab without the need to manually add a slash.

&ast; Dolphin automatically shows a new auto-completion list after auto-completion of a folder name. I think this is nice because it makes it possible to immediately see the contents of the new folder and continue navigation by chosing one of its sub-folders.

At the moment, the need to manually add a slash after every directory in nested paths is really annoying (on German keyboards, the slash is Shift + 7, a two-hands combo). 
Additionally, it is common practice to trigger auto-completion and appearance of auto-completion lists by pressing tab, not by typing a slash (or even deleting and typing it again).

**Comment by agaida** [comment]
just tested this - never used it before. Suggestions:
* tab should complete with trailing slash + regenerated list (the dolphin behaviour, if i understand right)
* the list should stop at the and and not jump to the start, this is horrible
* the list should have a few more lines - maybe a option for that would be helpful

**Comment by tsujan** [comment]
Oh, this is here since 2015!!

OK, I'll try to understand what @joshuakraemer and @agaida described and implement them. Probably more discussion will be needed.

**Comment by tsujan** [comment]
Until there's a consensus about this, I could do nothing.

**Comment by stefonarch** [comment]
I'm only missing (much) the trailing slash, I use often the navigation in the bar.

**Comment by tsujan** [comment]
> ... I use often the navigation in the bar.

I do so too but haven't found typing a simple slash difficult ;)

**Comment by stefonarch** [comment]
Here it is shift+7 to press, not so handy, in us layout it's different, one key.

**Comment by tsujan** [comment]
Understood.
This report is good only as a reference, not as a start point. I might open a feature request for slash and add it -- with low priority though.

**Comment by Niall-** [comment]
There should be clear consensus that a trailing slash should always be added to a tab completion on an unambiguous directory name, that is to say that "/hom[tab]" should always result in "/home/", and never "/home" as is the case now. Adding a trailing slash in such cases is the default behaviour for most shells (i.e., Bash, Zsh), and is the default behaviour in most other file managers (i.e., Dolphin, Thunar, Nautilus, even the GTK version of PCManFM).
It may not be much work to type the slash out on some keyboard layouts, but the issue was originally about having a single key allowing full path completion after all. :-) It does becomes tedious to type the slash out when you need to go several directories deep and you need to do this frequently.

It seems like the question of how to handle ambiguous directory names is holding this issue up, when to me at least it feels like it should be a separate issue. But regardless of that, here are some thoughts on the matter and some notes on how the programs listed above handle it (with the exception of Nautilus). The test folder looks like this: "mkdir -p testing/{desktop,downloads,downloads1,downloadssss}".

- $ ls desk[tab]
As this is an unambiguous directory, every program listed above adds a trailing slash: "\~/testing/desktop/", it is only PCManFM-Qt that does not add a trailing slash.
- $ ls down[tab]
This is an ambiguous directory name. The behaviour in Bash, Thunar, PCManFM-GTK, as well as PCManFM-Qt is to complete to "\~/testing/downloads" but **does not** to add a trailing slash. This is very common behaviour and is arguably the most default behaviour.
In Dolphin what happens is that it completes to "\~/testing/downloads/" but further presses of the tab key cycle through the other directories, i.e., it cycles through "\~/testing/downloads{,1,sss}/" and all of these **do** have a trailing slash. In Zsh, "$ ls down[tab]" completes to "$ ls downloads" like Bash, a second tab shows the list of files i.e., "downloads/     downloads1/    downloadssss/" again like Bash, but a third press puts you in the same mode that Dolphin does and you can then cycle through "\~/testing/downloads{,1,sss}/". Both Dolphin and Zsh loop around, this is the behaviour that @joshuakraemer  mentions and @agaida dislikes.

The first method that is the default on Bash seems like the least controversial, it is the least ergonomic but it the behaviour that most people should be familiar with. It also seems the easiest to implement - if the directory name is unambiguous as "desktop" is in this example, then you add a trailing slash. If it is unambiguous like "down[tab]" is then you do not need to change anything as PCManFM-Qt already completes to "downloads" but does not add a trailing slash.

I hope this helps.

**Comment by tsujan** [comment]
@Niall- I didn't understand what you meant by "ambiguous" and "unambiguous". To me, "desk" and "down" aren't different; if "desk" is "unambiguous", "down" is so too.

Frankly, every time a comment was added to this page, I remembered that I'd forgotten it but, after a short time, another exciting problem/feature attracted my attention, making me forget it again ;) That won't happen this time. I'll start to do this -- if you hate it, we could have another discussion after its implementation:

When the completion list is shown, Tab should select its rows and add the corresponding string with an ending slash. Backtab should do the same thing but in the opposite direction.

**Comment by Niall-** [comment]
Hi, by ambiguous/unambiguous I mean that in this specific scenario the only thing 'desk' can complete to is 'desktop', but 'down' can complete to either 'downloads', 'downloads1', or 'downloadssss' so some additional user input is required.

Thanks for the quick reply. Hopefully I haven't distracted you from something more exciting than this. :-)

**Comment by tsujan** [comment]
> Hopefully I haven't distracted you from something more exciting than this. :-)

Conversely, you made it exciting with your comment.

I may have gone in Dolphin's direction; I don't know. But I think it's logical to select a row when Tab/Backtab is pressed in both cases. In the case of an unambiguous string, there's only one row. If users don't like it for objective reasons -- not because of differences in tastes -- I'll be here to change it.

While working on it, I also found other problems with auto-completion; will try to fix all of them in one PR.

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/libfm-qt/pull/444

The job was more complex than I thought but the patch is simple.

**Comment by tsujan** [comment]
BTW, with languages that don't have a single key for slash, the first slash will be automatically added if `Tab` is pressed twice and the remaining slashes will be added by `Tab`. In general, there's no need to type slash with any language although the path-bar doesn't have an ending slash by default.

**Comment by joshuakraemer** [comment]
Thank you for finally implementing this! :thumbsup:

**Comment by tsujan** [comment]
> Thank you for finally implementing this!

Sorry for the long delay! With V0.14.1, libfm-qt and pcmanfm-qt finally reached a state that I could call stable; previously, more important issues were found, which should have been fixed before this.
