### ISSUE TITLE
A loop device mounted with udisksctl cannot be unmounted in pcmanfm-qt

### ISSUE THREAD

**Issue by Rabcor** [lxqt/pcmanfm-qt#2054]
If I use this simple bash script to mount an image file (iso/mdf/img)
```
LOOP=$(udisksctl loop-setup --file "$@" | sed 's/.* \([^ ]*\)\.$/\1/')
udisksctl mount --block-device $LOOP
```

It will show up in pcmanfm-qt as expected.

But if I click the eject button to unmount it, the eject button disappears but the image stays mounted.

To unmount it properly I have to follow this process:

- Click eject to unmount
- Click on the device to access it so pcmanfm-qt re-detects it which makes the eject button reappear
- Click eject to unmount again

However, if I cut out the `udisksctl mount --block-device $LOOP` part of the script, pcmanfm-qt will create a an automount popup and if it's mounted through that it can be ejected normally.

**Comment by tsujan** [comment]
Most probably fixed in https://github.com/lxqt/libfm-qt/commit/63f3cefca42c67fde66f5f18eef633639b58d606

If you can use git, try that commit. Otherwise, please install Thunar and test with it; if Thunar is OK, the above commit fixes it; if not, nothing could be done.

Also, please always add the versions requested in the report template.

**Comment by Rabcor** [comment]
> Most probably fixed in [lxqt/libfm-qt@63f3cef](https://github.com/lxqt/libfm-qt/commit/63f3cefca42c67fde66f5f18eef633639b58d606)

Nah it didn't fix it.

I tried with thunar, it doesn't have an eject button like pcmanfm-qt but right clicking to unmount produces identical behavior.

**Comment by tsujan** [comment]
Thanks for testing with Thunar. It shows there's a clash between GIO and your script. Nothing can be done here.
