### ISSUE TITLE
pcmanfm-qt should respect xdg-settings

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#961]
It would be really nice if pcmanfm-qt would respect XDG settings like XDG_CONFIG_DIRS. Right now it does not. 

```
$ echo $XDG_CONFIG_DIRS 
/etc:/etc/xdg:/usr/share
```
but pcmanfm-qt start searching for a configuration in /etc/xdg. /usr/share never will be read. If no vaild configuration is found pcmanfm-qt take hard wired defaults from pcman/settings.cpp. Falling back to this mechanism should be the last resort and normally not reached.

```
pcmanfm/settings.cpp:    suCommand_ = settings.value("SuCommand", "lxqt-sudo %s").toString();
```
not so nice, we should change it.

**Comment by agaida** [comment]
more verbose: we should change searching for valid configurations and the fallback (last resort) in settings.cpp too.

**Comment by tsujan** [comment]
Every Qt5 app automatically does that.

I haven't paid attention to that part of the code; maybe, it's old. Will look into it when I find time.

**Comment by agaida** [comment]
ok - but we should really read /usr/share/pcmanfmqt/foo - we do it for nearly all other parts of LXQt
(except the shortcut config i guess) - was not brave enough to change the daemon code :)

**Comment by tsujan** [comment]
`QSettings` does that when it's left to itself.

**Comment by agaida** [comment]
It seems that we had overridden it. I had a full strace, no statx, no read, nothing. Please test yourself.

**Comment by tsujan** [comment]
Yes, a glance at the code confirmed that. Perhaps, it was needed in old times. Tomorrow, I'll work on it but before doing anything, https://github.com/lxqt/pcmanfm-qt/pull/957 should be completed (unimportant changes have remained).

**Comment by agaida** [comment]
no problem, did a re-upload with a fixed patch

**Comment by tsujan** [comment]
OK, it's very easy. I first read and test https://github.com/lxqt/pcmanfm-qt/pull/957 again. If nothing wrong is found, I'll merge it (will do the reaming trivial things later) and then will make a PR for you to test.

**Comment by agaida** [comment]
Don't hurry, i cant upload it to debian - only minimal patchsets are allowed. So we can take our time. I just stumbled over it while testing the new package.

**Comment by tsujan** [comment]
Can't stop after starting ;) It'll take some time though because I should change my future PRs too -- https://github.com/lxqt/pcmanfm-qt/pull/957 is big.

**Comment by tsujan** [comment]
@agaida The PR is here: https://github.com/lxqt/pcmanfm-qt/pull/962

Although I know you'll do it but still:

Please test everything about it (not just `/usr/share`). There's no rush at all.

**Comment by tsujan** [comment]
Not related to the current page directly but worth asking:

On my work system (Manjaro), root config directory is `/root/.config`, where it should be.

But on the installed Buster ISO, it's `/.config` — if I open any Qt app as root, it writes its settings inside `/.config` on exiting. Is that intentional?

Moreover, on Buster, there's a weird thing: Qt reports the root config dir as `//.config` (with double slash). Although that has no effect (all computations seem right), I think something may be wrong on Buster.

It may be worth mentioning that I use my [black-list approach](https://github.com/lxqt/lxqt-sudo/pull/30/files) with lxqt-sudo — I don't know if it has any relevance to this.

**Comment by agaida** [comment]
it isn't - it will be created if  pcmanfm-qt is called via lxsudo - that means that something isn't set right or we stripped to much.

**Comment by agaida** [comment]
the homedir should be set i guess - as in
$( getent passwd "root" | cut -d: -f6 )
or better
HOME=$( getent passwd "$USER" | cut -d: -f6 )

**Comment by tsujan** [comment]
> Hmm - i guess HOME and TERM can be useful

I have both because, as it's clear from that long discussion last year, I believe in unsettling of dangerous EVs, which are only a few.

**Comment by agaida** [comment]
``` diff
set-term-and-home] % git diff
diff --git a/sudo.cpp b/sudo.cpp
index 83ffe3d..6fce827 100644
--- a/sudo.cpp
+++ b/sudo.cpp
@@ -87,6 +87,7 @@ namespace
     //Note: array must be sorted to allow usage of binary search
     static constexpr char const * const ALLOWED_VARS[] = {
         "DISPLAY"
+            , "HOME"
             , "LANG"
             , "LANGUAGE"
             , "LC_ADDRESS"
```
don't give anything useful for HOME
```
% lxsudo env
lxqt-sudo: Stripping child environment except for: DISPLAY, HOME, LANG, LANGUAGE, LC_ADDRESS, LC_ALL, LC_COLLATE, LC_CTYPE, LC_IDENTIFICATION, LC_MEASUREMENT, LC_MESSAGES, LC_MONETARY, LC_NAME, LC_NUMERIC, LC_PAPER, LC_TELEPHONE, LC_TIME, PATH, QT_PLATFORM_PLUGIN, QT_QPA_PLATFORMTHEME, TERM, WAYLAND_DISPLAY, XAUTHLOCALHOSTNAME, XAUTHORITY
SUDO_GID=1000
LANGUAGE=
LC_TIME=de_DE.UTF-8
USER=root
HOME=/home/agaida
LC_MONETARY=de_DE.UTF-8
QT_QPA_PLATFORMTHEME=lxqt
SUDO_UID=1000
LOGNAME=root
TERM=xterm-256color
LC_COLLATE=de_DE.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DISPLAY=:0
LANG=de_DE.utf8
XAUTHORITY=/home/agaida/.Xauthority
SUDO_COMMAND=/bin/sh -c unset LC_ALL; exec 'env'
SHELL=/bin/zsh
SUDO_USER=agaida
LC_MEASUREMENT=de_DE.UTF-8
PWD=/home/agaida/work/code/pkg-main/lxqt-sudo
LC_NUMERIC=de_DE.UTF-8
QT_PLATFORM_PLUGIN=lxqt
```

**Comment by tsujan** [comment]
I'm happy with black-list approach for years; have no reason to change it ;)

**Comment by agaida** [comment]
second - we don't strip LC_ALL, but unset it in the command - and nex question - why we use exec?
```
(git)-[set-term-and-home] % sudo env
DISPLAY=:0
LANG=de_DE.utf8
LANGUAGE=
LC_COLLATE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TERM=xterm-256color
XAUTHORITY=/home/agaida/.Xauthority
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
COLORTERM=yes
MAIL=/var/mail/root
LOGNAME=root
USER=root
HOME=/root
SHELL=/bin/zsh
SUDO_COMMAND=/usr/bin/env
SUDO_USER=agaida
SUDO_UID=1000
SUDO_GID=1000
```
it might be that you are happy, but HOME is false per definition compared to plain `sudo` :tongue:

**Comment by tsujan** [comment]
Restarting that long discussion? I won't ;) For me, the proof is in 3 years of practice.

**Comment by agaida** [comment]
and HOME is false - and i don't want to discuss it

**Comment by agaida** [comment]
lxsudo - HOME not stripped
```
HOME=/home/agaida
```
sudo
```
HOME=/root
```
thats the only thing i'm interested in right now.

**Comment by agaida** [comment]
The effect is:

Configpath:
$HOME + "/" + ".configure" := //.configure - thats exactly the problem we face right now.

**Comment by tsujan** [comment]
I know.

**Comment by agaida** [comment]
so - what speak agianst to make it right™ and evaluate `/etc/passwd` - we had to, because if we not strip HOME the value would be just plain wrong. Should be a oneliner.

**Comment by tsujan** [comment]
Report it at lxqt-sudo. As far as I tested in Buster, it had no bad consequence for LXQt apps. I don't defend it at all (here, root's home is `/root`).

**Comment by tsujan** [comment]
What I said about long discussion wasn't about this but about black-vs-white list approach. Let's not revive the latter.

**Comment by agaida** [comment]
i don't want to - i only want a right set HOME - and please for god and users sake please don't let me write it ;D

**Comment by ramajd** [comment]
Hi, 

Just wanted to know if you have any plan to fix this issue?

we are working on a distro based on [Guix](https://guix.gnu.org) (with a transactional package manager and read-only profiles concept) with LXQt as default desktop. 

we need to provide a series of default configurations for desktop, and since Guix is a source based distribution, and all packages are compiled directly from source code, we are using `XDG_CONFIG_DIR` (pointing to system-wide / user profiles ) to provide default configurations for desktop.

since `pcmanfm-qt` is not follow the `XDG_CONFIG_DIR` rules, we faced an issue about providing the default configurations for that.

our current solution is to fork this project and apply our patches above. but it's not preferable since the users expect to install the software directly from it's original maintainer repository.

Regards, 

--
Reza
PantherX Team
https://pantherx.org

**Comment by tsujan** [comment]
@ramajd What are you talking about? The issue was closed last year because it was fixed by its corresponding PR.

**Comment by ramajd** [comment]
@tsujan reviewing your reply on regarding commit, https://github.com/lxqt/pcmanfm-qt/commit/bc9a72cb9cc2ea9d2002f77c240b653edfd005bf#commitcomment-33504247 I assumed that this issue is still wont fixed. besides that we still face this issue in our environment.

**Comment by tsujan** [comment]
Please read https://github.com/lxqt/pcmanfm-qt/commit/bc9a72cb9cc2ea9d2002f77c240b653edfd005bf#commitcomment-33503759

In short, we inherited this structure and backward-compatibility can't be sacrificed for a special (and unimportant) use case. Adding lots of artificial codes to keep backward-compatibility not only would be ugly but also would negatively affect the startup.

After all, this is just about the app's default settings. If they're intolerable for your project, fork it.

**Comment by ramajd** [comment]
@tsujan ok, thanks for your quick response.

of course the backward compatibility is an important thing that needs to be kept. so maybe this issue needs a `won't fix` label.

**Comment by franzos** [comment]
> backward-compatibility can't be sacrificed for a special (and unimportant) use case

@tsujan Sounds like what Kernel developers do: "This is a bug but we won't fix it, because it would break a feature that relies on this bug." Is this the right approach?

> Adding lots of artificial codes to keep backward-compatibility not only would be ugly

You just mentioned, that you keep this code for backwards compatibility. Now you are arguing, that this would be "ugly" and have a "negative" impact. 

It seems to me that supporting XDG spec is desired and even expected. 
Why would LXQt take a different approach here?

I'm not an expert, but it seems this is not at all, a special use-case and even though it won't be fixed right now, this is still an issue - and thus, should remain _open_.

**Comment by tsujan** [comment]
> You just mentioned, that you keep this code for backwards compatibility. Now you are arguing, that this would be "ugly" and have a "negative" impact.

There's no contradiction in that. You could "enforce" backward-compatibility by adding lots of codes that are very ugly and...

> Why would LXQt take a different approach here?

It didn't. This is a special case, as far as I remember.

> I'm not an expert, but it seems this is not at all, a special use-case

It is. The app has some default values and the user could easily change them in Preferences. Now, some developers may not be satisfied with the defaults for whatever reason. No big deal.
